/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as InvoicesIndexImport } from './routes/invoices/index'
import { Route as ContactsIndexImport } from './routes/contacts/index'
import { Route as ContactsCreateImport } from './routes/contacts/create'
import { Route as ContactsContactIdImport } from './routes/contacts/$contactId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InvoicesIndexRoute = InvoicesIndexImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsIndexRoute = ContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsCreateRoute = ContactsCreateImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactIdRoute = ContactsContactIdImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      id: '/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ContactsCreateImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts': typeof ContactsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts': typeof ContactsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts'
    | '/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts/'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsCreateRoute: typeof ContactsCreateRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsCreateRoute: ContactsCreateRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts/$contactId",
        "/contacts/create",
        "/contacts/",
        "/invoices/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contacts/$contactId": {
      "filePath": "contacts/$contactId.tsx"
    },
    "/contacts/create": {
      "filePath": "contacts/create.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.tsx"
    },
    "/invoices/": {
      "filePath": "invoices/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
